import productImg from "../../assets/proImage.png";
export const products = [
  {
    id: 1,
    name: "100% Butter French Croissants",
    code: "in stock",
    star: 4,
    price: 14.44,
    originalPrice: null,
    image: productImg,
  },
  {
    id: 2,
    name: "All Natural Italian-Style Chicken Australia",
    code: "in stock",
    star: 5,
    price: 0.35,
    originalPrice: 7.25,
    image: productImg,
  },
  {
    id: 3,
    name: "American Cheese Singles",
    code: "in stock",
    star: 3,

    price: 3.29,
    originalPrice: null,
    image: productImg,
  },
  {
    id: 4,
    name: "Angus Rosenblickegap Sweet & Salty Kettle Corn",
    code: "in stock",
    star: 4,
    price: 2.29,
    originalPrice: 4.19,
    image: productImg,
  },
  {
    id: 5,
    name: "Blue Diamond Almonds Lightly Salted",
    code: "in stock",
    star: 4,
    price: 11.88,
    originalPrice: null,
    image: productImg,
  },
  {
    id: 6,
    name: "Blueberries - 1 Pint Package",
    code: "in stock",
    star: 4,
    price: 3.89,
    originalPrice: 4.4,
    image: productImg,
  },
  {
    id: 7,
    name: "Canada Dry Ginger Ale - 2 L Bottle",
    code: "in stock",
    star: 3,
    price: 3.85,
    originalPrice: 5.45,
    image: productImg,
  },
  {
    id: 8,
    name: "Challenge Spreadable Butter",
    code: "in stock",
    star: 4,
    price: 7.58,
    originalPrice: null,
    image: productImg,
  },
  {
    id: 9,
    name: "Chobani Complete Vanilla Greek Yogurt",
    code: "in stock",
    star: 4,
    price: 4.49,
    originalPrice: 6.1,
    image: productImg,
  },
  {
    id: 10,
    name: "Coca-Cola - 2 L Bottle",
    code: "in stock",
    star: 4,
    price: 3.85,
    originalPrice: null,
    image: productImg,
  },
  {
    id: 11,
    name: "Encore Seafoods Surfited Alaskan Salmon",
    code: "in stock",
    star: 4,
    price: 27.48,
    originalPrice: null,
    image: productImg,
  },
  {
    id: 12,
    name: "Fairlife Lactose-Free 2% Milk",
    code: "in stock",
    star: 4,
    price: 3.69,
    originalPrice: null,
    image: productImg,
  },
];
